Cleaning up GSM8k's `CalculatorEnv` a bit
Future-House/aviary pull request #164
Opened 2024-12-28 19:53 UTC by jamesbraza

- Standardized `self.tools` population to within `reset` and removed extra tools attributes
- Added `exc` to the failure message on `calculator`
- Improved the docstring by removing type hint duplication and fixing returns message

2024-12-28 19:56 UTC, sidnarayanan requested changes

2024-12-28 19:56 UTC, sidnarayanan commented on packages/gsm8k/src/aviary/envs/gsm8k/env.py
> +                element is a boolean indicating if this action is terminal.
Let's not do docstring changes right now, since this may affect performance and require rerunning experiments.

2024-12-28 19:56 UTC, sidnarayanan commented on packages/gsm8k/src/aviary/envs/gsm8k/env.py
> +                f"Error using calculator: {exc!r}.",
As above - this changes the MDP. Let's wait until the paper is out.

2025-01-02 19:50 UTC, jamesbraza commented on packages/gsm8k/src/aviary/envs/gsm8k/env.py
> +                f"Error using calculator: {exc!r}.",
Okay, the paper is out, resolving this one and [this other one](https://github.com/Future-House/aviary/pull/164#discussion_r1898981343) and re-requesting

2025-01-02 20:01 UTC, sidnarayanan approved these changes

2025-01-02 20:20 UTC, merged